//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoCenterEntities : DbContext
    {
        private static AutoCenterEntities _context;
        public AutoCenterEntities()
            : base("name=AutoCenterEntities1")
        {
        }

        public static AutoCenterEntities GetContext()
        {
            if (_context== null)
                _context = new AutoCenterEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auto> Auto { get; set; }
        public virtual DbSet<AutoService> AutoService { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<EngineType> EngineType { get; set; }
        public virtual DbSet<JobTitle> JobTitle { get; set; }
        public virtual DbSet<Model> Model { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TestDrive> TestDrive { get; set; }
        public virtual DbSet<Vendor> Vendor { get; set; }
    }
}
